# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/limbo-lbl-gen',
                'doc_host': 'https://azaidi06.github.io',
                'git_url': 'https://github.com/azaidi06/limbo-lbl-gen',
                'lib_path': 'limbo_lbl_gen'},
  'syms': {'limbo_lbl_gen.core': {'limbo_lbl_gen.core.foo': ('core.html#foo', 'limbo_lbl_gen/core.py')}}}
